version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.0

description: |
  Syncs circleci machine ip with aws security group

examples:
  basic_commands:
    description: "Examples uses aws security group ip sync"
    usage:
      version: 2.1
      orbs:
        aws-security-group-ip: apprl/aws-security-group-ip@1.0.0
      jobs:
        build:
          docker:
            - image: circleci/python:2.7
          steps:
            - aws-security-group-ip/sync:
                security_group: aws-security-group


commands:
  test-helm:
    parameters:
      kubeconfig:
        type: string
    steps:
      - run:
          name: Test helm
          command: |
            public_ip_address=$(wget -qO- http://checkip.amazonaws.com)
            echo "This computers public ip address is $public_ip_address region $AWS_DEFAULT_REGION"
            helm version --kube-context=<<parameters.kubeconfig>>
  copy-kubeconfig:
    steps:
      - run:
          name: Copy kubeconfig from workspace
          command: |
            mkdir /root/.kube
            cp workspace/kubeconfig/config.yaml ~/.kube/config;
  sync-ips-to-aws-security-group:
    description: "Syncs circleci machine ip with aws security group"
    parameters:
      security_group:
        type: string
    steps:
      - run:
          name: Insall aws cli
          command: |
            apk --no-cache update && \
              apk --no-cache add python py-pip py-setuptools ca-certificates groff less && \
              pip --no-cache-dir install awscli==1.15.47 && \
              apk add git openssh make jq bash && \
              rm -rf /var/cache/apk/*
      - run:
          name: Remove ips form security group
          command: wget -O - https://raw.githubusercontent.com/apprl/circleci-orb/master/orb/aws-security-group-ip/remove-ips-from-sg.sh | AWS_SECURITY_GROUP=<<parameters.security_group>> bash
      - run:
          name: Add ip to security group
          command: wget -O - https://raw.githubusercontent.com/apprl/circleci-orb/master/orb/aws-security-group-ip/add-ip-to-sg.sh | AWS_SECURITY_GROUP=<<parameters.security_group>> bash

jobs:
  download-kubeconfig:
    parameters:
      kubeconfig:
        type: string
      working_directory:
        type: string
    working_directory: <<parameters.working_directory>>
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: "Setup aws retion environment variables"
          command: echo 'export AWS_REGION="$AWS_DEFAULT_REGION"' >> $BASH_ENV
      - aws-s3/copy:
          from: <<parameters.kubeconfig>>
          to: 'kubeconfig/config.yaml'
      - persist_to_workspace:
          root: .
          paths:
            - kubeconfig
