version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.0

description: |
  Syncs circleci machine ip with aws security group

examples:
  basic:
    description: "Examples uses of apprl circleci tools"
    usage:
      version: 2.1
      orbs:
        apprl-circleci-tools: apprl/apprl-circleci-tools@1.0.0
      jobs:
        build:
          docker:
            - image: circleci/python:2.7
          steps:
            - apprl-circleci-tools/sync-ips-to-aws-security-group:
                security_group: aws-security-group
            - apprl-circleci-tools/copy-kubeconfig
            - apprl-circleci-tools/setup-helm
            - apprl-circleci-tools/test-helm:
                kubeconfig: config.file

      workflows:
        test-build-deploy:
          jobs:
            - apprl-circleci-tools/download-kubeconfig:
                working_directory: ~/dir
                kubeconfig: s3://path/to/kubectl/config.yaml
                context: aws




commands:
  setup-helm:
    steps:
      - run:
          command: |
            helm init --client-only
            helm plugin install https://github.com/hypnoglow/helm-s3.git
            AWS_DEFAULT_REGION=eu-west-1 helm repo add apprlcharts s3://apprl-development/k8s/charts
            helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
            helm repo list
  test-helm:
    parameters:
      kubeconfig:
        type: string
    steps:
      - run:
          name: Test helm
          command: |
            public_ip_address=$(wget -qO- http://checkip.amazonaws.com)
            echo "This computers public ip address is $public_ip_address region $AWS_DEFAULT_REGION"
            helm version --kube-context=<<parameters.kubeconfig>>
  copy-kubeconfig:
    steps:
      - run:
          name: Copy kubeconfig from workspace
          command: |
            mkdir /root/.kube
            cp workspace/kubeconfig/config.yaml ~/.kube/config;
  sync-ips-to-aws-security-group:
    description: "Syncs circleci machine ip with aws security group"
    parameters:
      security_group:
        type: string
    steps:
      - run:
          name: Insall aws cli
          command: |
            apk --no-cache update && \
              apk --no-cache add python py-pip py-setuptools ca-certificates groff less && \
              pip --no-cache-dir install awscli==1.15.47 && \
              apk add git openssh make jq bash && \
              rm -rf /var/cache/apk/*
      - run:
          name: Remove ips form security group
          command: wget -O - https://raw.githubusercontent.com/apprl/circleci-orb/master/orb/apprl-circleci-tools/remove-ips-from-sg.sh | AWS_SECURITY_GROUP=<<parameters.security_group>> bash
      - run:
          name: Add ip to security group
          command: wget -O - https://raw.githubusercontent.com/apprl/circleci-orb/master/orb/apprl-circleci-tools/add-ip-to-sg.sh | AWS_SECURITY_GROUP=<<parameters.security_group>> bash

jobs:
  download-kubeconfig:
    parameters:
      kubeconfig:
        type: string
      working_directory:
        type: string
    working_directory: <<parameters.working_directory>>
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: "Setup aws retion environment variables"
          command: echo 'export AWS_REGION="$AWS_DEFAULT_REGION"' >> $BASH_ENV
      - aws-s3/copy:
          from: <<parameters.kubeconfig>>
          to: 'kubeconfig/config.yaml'
      - persist_to_workspace:
          root: .
          paths:
            - kubeconfig
